### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nabr2730** [NanairoServerNetwork/nanairo_server_infra#9]
## Worker-0の復旧
- [ ] docker入れる
- [ ] tunnel生やす
- [ ] grafana生やす
##  ロビーの復旧
- [ ] Worker-0が完全復旧完了したら参加可能
## 冗長化
- [ ] ProxyNodeを1台から3台に増強
- [ ] CloudflareSpectrumの直下に配置されるサーバーにHAProxy導入
- [ ] 各子ノードにDocker,Velocity導入
## ロビーのDocker化
note: すべてのデータを永続化する
- [ ] VM: mc-Worker01 を作成
- [ ] DockerImageを作成
- [ ] Dockerに置き換え
- [ ] tunnelを `192.168.2.11` から `192.168.4.1` に張替え

**Comment by nabr2730** [comment]
寝ても許してね

**Comment by nabr2730** [comment]
#10
